FoodService/FoodService/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FoodService.Models;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Http;

namespace FoodService.Controllers
{
    public class BasketController : Controller
    {
        private readonly IFoodsService _foodService;

        public BasketController(IFoodsService foodService)
        {
            _foodService = foodService;
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            base.OnActionExecuted(context);

            ViewBag.Categories = _foodService.Categories.ToArray();
        }

        [HttpGet]
        public IActionResult Index()
        {
            var customer = _foodService.GetCustomer(HttpContext.Session.GetString("user"));

            if (customer == null)
                return RedirectToAction("Index", "Home");

            var basket = _foodService.GetBasketByCustomerId(customer.Id);

            if (basket == null)
                return RedirectToAction("Index", "Home");

            basket.OrderedFoods = _foodService.GetNonOrderedFoodsByBasketId(basket.Id);

            return View(basket);
        }

        public ActionResult Add(Int32 foodId)
        {
            var customer = _foodService.GetCustomer(HttpContext.Session.GetString("user"));
            if (customer == null)
                return RedirectToAction("Index", "Home");

            var basket = _foodService.GetBasketByCustomerId(customer.Id);
            if (basket == null)
                return RedirectToAction("Index", "Home");

            Food food = _foodService.GetFood(foodId);
            if (basket.TotalPrice + food.Price <= 20000)
            {
                _foodService.AddFoodToFoodBasket(basket.Id, food.Id);
                basket.TotalPrice += food.Price;
            }
            _foodService.UpdateBasket(basket);

            return RedirectToAction("Index");
        }

        public ActionResult Remove(Int32 foodId)
        {
            var customer = _foodService.GetCustomer(HttpContext.Session.GetString("user"));
            if (customer == null)
                return RedirectToAction("Index", "Home");

            var basket = _foodService.GetBasketByCustomerId(customer.Id);
            if (basket == null)
                return RedirectToAction("Index", "Home");


            Food food = _foodService.Foods.FirstOrDefault(f => f.Id == foodId);
            basket.TotalPrice -= food.Price;

            _foodService.UpdateBasket(basket);
            _foodService.RemoveFoodFromFoodBasket(basket.Id, food.Id);

            basket.OrderedFoods = _foodService.GetNonOrderedFoodsByBasketId(basket.Id);

            return View("Index", basket);
        }

        public ActionResult EmptyBasket()
        {
            var customer = _foodService.GetCustomer(HttpContext.Session.GetString("user"));
            if (customer == null)
                return RedirectToAction("Index", "Home");

            var basket = _foodService.GetBasketByCustomerId(customer.Id);
            if (basket == null)
                return RedirectToAction("Index", "Home");

            basket.TotalPrice = 0;
            _foodService.UpdateBasket(basket);

            List<Food> foods = _foodService.GetNonOrderedFoodsByBasketId(basket.Id);

            foreach (Food food in foods)
            {
                _foodService.RemoveFoodFromFoodBasket(basket.Id, food.Id);
            }

            return RedirectToAction("Index");
        }

        public FileResult ImageForFood(Int32? foodId)
        {
            Byte[] imageContent = _foodService.GetFoodMainImage(foodId);

            if (imageContent == null)
                return File("~/images/NoImage.png", "image/png");

            return File(imageContent, "image/png");
        }

        public FileResult BasketImage()
        {
            return File("~/images/basketImage.png", "image/png");
        }
    }
}

FoodService/FoodService/Views/Shared/_Layout.cshtml
@using FoodService.Models;
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FoodService website</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
    </environment>
</head>
<body>
    <div class="header">
        <div class="headerText">
            <h1>
                <a asp-controller="Home" asp-action="Index">FoodService</a>
            </h1>
            <h3>
                The main service for getting food
            </h3>
        </div>
        @if (Context.Session.GetString("user") != null)
        {
            <div class="basketPlace">
                <a asp-controller="Basket" asp-action="Index"><img src="@Url.Action("BasketImage")" class="basketIcon" /></a>
            </div>
        }
    </div>
    <div class="headerAdmin">
        @if (Context.Session.GetString("user") == null)
        {
            <table>
                <tr>
                    <td>
                        <a asp-controller="Account" asp-action="Login">Login</a>
                    </td>
                    <td>
                        <a asp-controller="Account" asp-action="Register">Registration</a>
                    </td>
                </tr>
            </table>
        }
        else
        {
            <table>
                <tr>
                    <td colspan="2">
                        Welcome, @Context.Session.GetString("user")!
                    </td>
                </tr>
                <tr>
                    <td>
                        <a asp-controller="Account" asp-action="Logout">Logout</a>
                    </td>
                    <td></td>
                </tr>
                <tr></tr>
            </table>
        }
    </div>
    <div class="content">
        <div class="leftColumn">
            <h3>Searching by categories</h3>
            @if (ViewBag.Categories == null || ViewBag.Categories.Length == 0)
            {
                <span>There are no categories ?!.</span>
            }
            else
            {
                <ul>
                    @foreach (Category category in ViewBag.Categories)
                    {
                        <li>
                            <a asp-controller="Home" asp-action="List" asp-route-categoryId="@category.Id">@category.Name</a>
                        </li>
                    }
                </ul>
            }
        </div>
        <div class="rightColumn">
            @RenderBody()
        </div>
    </div>


    @RenderSection("Scripts", required: false)
</body>
</html>